# Build and deploy the static website for jonathan.fung.dev

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '13.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Publish and Deployment steps for master branch only
- task: PublishPipelineArtifact@1
  displayName: 'Publish public site artifact'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/public'
    artifactName: 'public-site'

- task: S3Upload@1
  displayName: Deploy public site to S3
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    awsCredentials: 'AWS S3 Service Connector'
    regionName: 'eu-west-2'
    bucketName: 'jonathan.fung.dev'
    sourceFolder: '$(System.DefaultWorkingDirectory)/public'
    globExpressions: '**'
    filesAcl: 'bucket-owner-read'